<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Nintenlord\Nintenlord.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Code\Preprocessors\Directives\IncludeExternal.cs" />
    <Compile Remove="Code\Templates\GenericFE8Ender.cs" />
    <Compile Remove="Code\Templates\GenericFE8Template.cs" />
    <Compile Remove="Collections\DefineCollection.cs" />
    <Compile Remove="Collections\DefineCollectionOld.cs" />
    <Compile Remove="IncludeToolEventAlias.cs" />
  </ItemGroup>
</Project>